# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_pagamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='valor',
            field=models.IntegerField(default=50),
        ),
    ]
