# Generated by Django 2.1.2 on 2018-10-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_pagamentos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
