# Generated by Django 2.1.2 on 2018-10-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_auto_20181023_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='pontuacao_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
