# Generated by Django 2.1.2 on 2018-10-23 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_auto_20181023_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Aprovado'), ('r', 'Reprovado')], max_length=55)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('descricao', models.CharField(max_length=255)),
                ('pontuacao_reprovacao', models.IntegerField()),
                ('pontuacao_aprovacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('criterios', models.ManyToManyField(to='avaliacao.Criterio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Nivel')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.Criterio'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.Prova'),
        ),
    ]
