# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel', models.CharField(choices=[('branco', 'Branco'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('azul claro', 'Azul Claro')], max_length=55)),
            ],
        ),
    ]
