# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Jan', 'Janeiro'), ('Fev', 'Fevereiro'), ('Mar', 'Mar\xe7o'), ('Abr', 'Abril'), ('Maio', 'Maio'), ('Jun', 'Junho'), ('Jul', 'Julho'), ('Ago', 'Agosto'), ('Set', 'Setembro'), ('Out', 'Outubro'), ('Nov', 'Novembro'), ('Dez', 'Dezembro')], max_length=55)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno')),
            ],
        ),
    ]
