# Generated by Django 2.1.2 on 2018-10-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20181024_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Nivel'),
        ),
    ]
